### ISSUE TITLE
Different cell_end behavior if \trowd not present 

### ISSUE THREAD

**Issue by micahjames** [kota7/striprtf#7]
I have some tables in rtf documents that appear to have their \trowd tag missing from the row entries. This seems to be causing strip_rtf to handle \cell differently. Here's a minimal example of the behavior:

> striprtf::strip_rtf("\\\\trowd AAA \\\\cell  BBB \\\\cell CCC \\\\cell")
[1] "*| AAA  | BBB  | CCC  | "
> striprtf::strip_rtf(" AAA \\\\cell  BBB \\\\cell CCC \\\\cell")
[1] " AAA \005BBB \005CCC \005"

For my own use, I'm just using the cell_end string as a place to split the output so I'm getting by with setting cell_end="\005", but this seems like it's unexpected behaviour.

Edit (sorry): My workaround didn't quite work. When I used strip_rtf with `cell_end="\005"`, the `"\005"`s in the output above become `"\006"`s instead.  So now I'm setting `cell_end="ZZZZ"` (a safe string for my files) and splitting the output with the pattern `"ZZZZ|\005"`.

**Comment by kota7** [comment]
I see.  Do you have a case in actual RTF file which does not have "\trowd" keyword for a tables?  Reading the RTF spec http://www.biblioscape.com/rtf15_spec.htm, I thought all rows must start from "\trowd".  If there is an RTF file like your second example, would you kindly share that with me?  I would love to take a look.

This behavior is due to the assumption that all rows must start from "\throwd".  If that is not always true (and is legal as RTF) then I will make an edit in the parsing process.

**Comment by micahjames** [comment]
Thank you for responding so quickly! 

Unfortunately, I cannot share the specific problematic document (as I'm sure there's more wrong with it than I'm able to point out here) but I was able to create a small example. What happens in the example is that the \row keyword appears right after the \trowd keyword and then an additional \row keyword appears at the end of the row.
[cells_outside_rows.zip](https://github.com/kota7/striprtf/files/1002043/cells_outside_rows.zip)

Here's what happens for me when this is processed.

> striprtf::read_rtf("~/cells_outside_rows.rtf")
[1] "*| "                          "AAA \005BBB \005CCC \005\003" "DDD \005EEE \005FFF \005"

-Micah

**Comment by kota7** [comment]
Thank you for this.  I played with the file a bit on my Windows MS word.  seems there are some problems on the table parsing process.  I will sort this out shortly and come up with a reasonable solutions.

**Comment by kota7** [comment]
The v0.4.5 has been released.  This version handles the table parser issue raised in this thread.  The example file @micahjames gave me is now parsed properly as: 
```r
> read_rtf("~/Desktop/cells_outside_rows.rtf")
[1] "*| AAA  | BBB  | CCC  | "
```

@micahjames, thank you for raising this issue.  I believe the parser became much more robust than before.  Please kindly let me know if you have some comment, question, or concern.

**Comment by kota7** [comment]
On CRAN now.
